### ISSUE TITLE
Error: ENOMEM, Cannot allocate memory on extractSecretKey

### ISSUE THREAD

**Issue by JaredCE** [chm-diederichs/minisign#3]
I am receiving an `Error: ENOMEM, Cannot allocate memory` when trying to use the `extractSecretKey` functionality.

my code looks like:

index.js
```
const fs = require('fs');
const Minisign = require('./src/Minisign');

const file = fs.readFileSync('/Users/jared/.minisign/minisign.key');
const miniSign = new Minisign('abcd', file);
miniSign.signFile('/Users/jared/filetosign.txt');
```

/src/Minisign.js
```
const minisign = require('minisign');
const fs = require('fs');

class Minisign {
  constructor(password, privateKey) {
    this.MINISIGN_PASSWORD = Buffer.from(password);
    this.MINISIGN_PRIVATE_KEY = privateKey;
  }

  signFile(filePath) {
    const privateKeyBuffer = minisign.parseSecretKey(this.MINISIGN_PRIVATE_KEY);
    const privateKey = minisign.extractSecretKey(
      this.MINISIGN_PASSWORD,
      privateKeyBuffer
    );
    console.log(privateKey);
  }
}

module.exports = Minisign;
```

Full error:

> /Users/jared/Projects/scratch/minisign-tests/node_modules/minisign/minisign.js:130
>   sodium.sodium_mprotect_readwrite(pwd)
>          ^
> 
> Error: ENOMEM, Cannot allocate memory
>     at Object.extractSecretKey (/Users/jared/Projects/scratch/minisign-tests/node_modules/minisign/minisign.js:130:10)
>     at Minisign.signFile (/Users/jared/Projects/scratch/minisign-tests/src/Minisign.js:14:33)
>     at Object.<anonymous> (/Users/jared/Projects/scratch/minisign-tests/index.js:10:10)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
>     at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
>     at startup (internal/bootstrap/node.js:285:19)
>

**Comment by chm-diederichs** [comment]
When allocating the password buffer in the constructor function, use `sodium.sodium_malloc()` from the `sodium-native` module.

`sodium.mprotect` methods won't work unless the buffer is secure in the first place. Let me know if it's still an issue.
